### ISSUE TITLE
internal crash

### ISSUE THREAD

**Issue by feivur** [Kunzisoft/Android-SwitchDateTimePicker#19]
05-15 18:54:00.560 E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnKeyListener(android.view.View$OnKeyListener)' on a null object reference
                                                at com.kunzisoft.switchdatetime.time.SwitchTimePicker.onCreateView(SwitchTimePicker.java:193)
                                                at com.kunzisoft.switchdatetime.SwitchDateTimeDialogFragment.onCreateDialog(SwitchDateTimeDialogFragment.java:251)
                                                at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312)
                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                at android.os.Looper.loop(Looper.java:135)
                                                at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                at java.lang.reflect.Method.invoke(Native Method)
                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by J-Jamet** [comment]
Can you tell me under what circumstances this exception is thrown?

**Comment by feivur** [comment]
I copyed sample code without changes from github readme to my project and
run from my fragment. I tryed both getFragmentManager and
getActivity().getSupportFragmentManager. I use latest support libs and
build tools versions.
I wish you to easy fix it!

15 мая 2017 г. 7:38 PM пользователь "Jérémy JAMET" <notifications@github.com>
написал:

**Comment by J-Jamet** [comment]
Have you tried getChildFragmentManager() ? If you call it from a fragment, you may need to use the second level of manager.
