### ISSUE TITLE
Application is throwing error as i click  open date time dialog button . Need help...!!!

### ISSUE THREAD

**Issue by nishantmendiratta** [Kunzisoft/Android-SwitchDateTimePicker#4]
48:53.631 14905-14905/in.example.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: in.example.android, PID: 14905
                                                                  android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class <unknown>
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                      at com.kunzisoft.switchdatetime.SwitchDateTimeDialogFragment.onCreateDialog(SwitchDateTimeDialogFragment.java:106)
                                                                      at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
                                                                      at android.os.Handler.handleCallback(Handler.java:746)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                   Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class <unknown>
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                      at com.kunzisoft.switchdatetime.SwitchDateTimeDialogFragment.onCreateDialog(SwitchDateTimeDialogFragment.java:106) 
                                                                      at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295) 
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682) 
                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541) 
                                                                      at android.os.Handler.handleCallback(Handler.java:746) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                      at com.kunzisoft.switchdatetime.SwitchDateTimeDialogFragment.onCreateDialog(SwitchDateTimeDialogFragment.java:106) 
                                                                      at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295) 
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682) 
                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541) 
                                                                      at android.os.Handler.handleCallback(Handler.java:746) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                   Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010006 a=-1}
                                                                      at android.content.res.TypedArray.getDrawable(TypedArray.java:867)
                                                                      at android.view.View.<init>(View.java:3957)
                                                                      at android.view.ViewGroup.<init>(ViewGroup.java:573)
                                                                      at android.widget.RelativeLayout.<init>(RelativeLayout.java:248)
                                                                      at android.widget.RelativeLayout.<init>(RelativeLayout.java:244)
                                                                      at android.widget.RelativeLayout.<init>(RelativeLayout.java:240)
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                      at com.kunzisoft.switchdatetime.SwitchDateTimeDialogFragment.onCreateDialog(SwitchDateTimeDialogFragment.java:106) 
                                                                      at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295) 
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682) 
                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541) 
                                                                      at android.os.Handler.handleCallback(Handler.java:746) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by nishantmendiratta** [comment]
After adding following lines to current theme, It got resolved.

+        <item name="dateTimeColorBackground">#a72a2a</item>
+        <item name="dateTimeColorLabel">#d7f7fc</item>
+        <item name="dateTimeColorValue">#e3f7d9</item>
+        <item name="dateTimeColorIcon">#ffffff</item>
